services:
  fraudlabspro.module:
    class: FraudLabsPro
    public: true
    factory: ["Module", "getInstanceByName"]
    arguments:
      - "fraudlabspro"

  fraudlabspro.context:
    class: Context
    public: true
    factory: ["Context", "getContext"]

  #####################
  # PS Account
  fraudlabspro.ps_accounts_installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    public: true
    arguments:
      - "5.0"

  fraudlabspro.ps_accounts_facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    public: true
    arguments:
      - "@fraudlabspro.ps_accounts_installer"

  #####################
  # PS Billing
  fraudlabspro.ps_billings_context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
      - "@fraudlabspro.ps_accounts_facade"
      - "@fraudlabspro.context"
      - false # if true you are in sandbox mode, if false or empty not in sandbox

  fraudlabspro.ps_billings_facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
      - "@fraudlabspro.ps_billings_context_wrapper"
      - "@fraudlabspro.module"

  fraudlabspro.ps_billings_service:
    class: PrestaShopCorp\Billing\Services\BillingService
    public: true
    arguments:
      - "@fraudlabspro.ps_billings_context_wrapper"
      - "@fraudlabspro.module"
